<?php
define('FOOTER_SIDEBAR_QUANTITY', 4);
define('CONTENT_BLOCK_CLASS', 'content-block');
define('CONTENT_BLOCK_CONTENT', CONTENT_BLOCK_CLASS . '__content');
define('CONTENT_BLOCK_MODIFIER', CONTENT_BLOCK_CLASS . '--');
